name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        host:
          [
            ubuntu-latest,
            macos-latest,
            windows-latest,
          ]
        include:
        - host: ubuntu-latest
          TARGET: x86_64-linux
          EXTENSION:
        - host: macos-latest
          TARGET: x86_64-macos
          EXTENSION:
        - host: windows-latest
          TARGET: x86_64-windows
          EXTENSION: .exe
    runs-on: ${{matrix.host}}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: "recursive"
    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v1
      with:
        version: master
    - name: Zig Build
      run: zig build -Dtarget=${{matrix.TARGET}} -Dcpu=baseline
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{matrix.TARGET}}-bayonnaise
        path: |
          zig-out/bin/bayonnaise${{matrix.EXTENSION}}
    - name: Zig Test
      run: zig build test
